### ISSUE TITLE
Incomplete? No module named 'cycle.gymdata'

### ISSUE THREAD

**Issue by bibbygoodwin** [sjtuzq/Cycle_Dynamics#2]
Hi @sjtuzq 

I am trying to run the XArm experiments as detailed in the README, and have downloaded the requisite datasets.

Unfortunately, on running `main.py` in `realxarm_exp/xarm_pose`, I get the following error:
~~~
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from cycle.model.cycle import CycleGANModel
  File "/Users/me/Code/Cycle_Dynamics/realxarm_exp/xarm_pose/cycle/model/cycle.py", line 19, in <module>
    from cycle.model.fmodel import Fmodel,ImgFmodel,ADmodel,AGmodel
  File "/Users/me/Code/Cycle_Dynamics/realxarm_exp/xarm_pose/cycle/model/fmodel.py", line 13, in <module>
    from cycle.gymdata import Robotdata,RobotStackFdata
ModuleNotFoundError: No module named 'cycle.gymdata'
~~~ 

The `cycle.gymdata` module does not appear to be defined anywhere within this codebase. Could you please point me to it if I have missed something?

Many thanks!

**Comment by bibbygoodwin** [comment]
Update: commenting out this import where it appears seems to fix things as on closer inspection it isn't used for the training process.
